# Generated by Django 5.0.6 on 2024-08-18 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=255)),
                ('contract_start_month', models.DateField()),
                ('contract_end_month', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteMonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('poa_irradiance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar.site')),
            ],
        ),
        migrations.CreateModel(
            name='InverterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inverter_name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverters', to='solar.sitemonthlydata')),
            ],
        ),
    ]
