# Generated by Django 5.0.6 on 2024-08-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_site_city_site_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='uid',
            new_name='site_id',
        ),
    ]
