# Generated by Django 5.0.6 on 2024-09-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_rename_uid_site_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemonthlydata',
            name='is_day',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
