# Generated by Django 5.0.6 on 2024-09-04 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0004_sitemonthlydata_is_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='InverterNameMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=100)),
                ('formatted_name', models.CharField(max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverter_name_mappings', to='solar.site')),
            ],
        ),
    ]
