# Generated by Django 5.0.6 on 2024-09-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0005_inverternamemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemonthlydata',
            name='meter_power',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='inverter_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitemonthlydata',
            name='POA_Irradiance',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sitemonthlydata',
            name='is_day',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
