# Generated by Django 5.0.6 on 2024-09-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0007_inverterdata_is_modified_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SiteMonthlyData",
            new_name="SiteHourlyData",
        )
    ]
