# Generated by Django 5.0.6 on 2024-09-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0008_remove_sitemonthlydata_site_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inverterdata",
            old_name="monthly_data",
            new_name="hourly_data",
        ),
        migrations.AddField(
            model_name="inverterdata",
            name="expected_value",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="inverterdata",
            name="is_exclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitehourlydata",
            name="action_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Action needed"),
                    ("B", "Manually investigated and approved/edited"),
                    ("C", "Added to exclusive outage"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitehourlydata",
            name="is_exclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SiteCumulativeMonthlySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_month", models.PositiveIntegerField()),
                (
                    "cumulative_actual_total",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "cumulative_expected_total",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "cumulative_availability",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="solar.site"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteDailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("actual_total", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "expected_total",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                ("availability", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="solar.site"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteMonthlySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_month", models.PositiveIntegerField()),
                ("actual_total", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "expected_total",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                ("availability", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="solar.site"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ExclusiveOutage",
        ),
    ]
