# Generated by Django 5.0.6 on 2024-09-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0009_rename_monthly_data_inverterdata_hourly_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitehourlydata',
            name='status',
            field=models.CharField(choices=[('A', 'A - No issues, no changes'), ('B', 'B - Issues, auto-corrected'), ('C', 'C - Issues, auto-corrected, manual investigation required')], default='A', max_length=1),
        ),
    ]
