# Generated by Django 5.0.6 on 2024-09-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0011_rename_hourly_data_inverterdata_site_hourly_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitehourlydata',
            name='status',
            field=models.CharField(choices=[('A', 'A - No issues, no changes'), ('B', 'B - Issues, auto-corrected'), ('C', 'C - Issues, auto-corrected, manual investigation required'), ('D', 'D - Unprocessed')], default='D', max_length=1),
        ),
    ]
