# Generated by Django 5.0.6 on 2024-09-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0012_alter_sitehourlydata_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sitemonthlysummary',
            constraint=models.UniqueConstraint(fields=('site', 'year_month'), name='unique_site_year_month'),
        ),
    ]
