# Generated by Django 5.0.6 on 2024-09-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0013_sitemonthlysummary_unique_site_year_month'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sitecumulativemonthlysummary',
            constraint=models.UniqueConstraint(fields=('site', 'year_month'), name='unique_cumulative_site_year_month'),
        ),
        migrations.AddConstraint(
            model_name='sitedailysummary',
            constraint=models.UniqueConstraint(fields=('site', 'date'), name='unique_site_date'),
        ),
    ]
